'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property UserID As Integer
    Public Property Street As String
    Public Property City As String
    Public Property StateCode As String
    Public Property PostalCode As String

    Public Overridable Property Orders As ICollection(Of Order) = New HashSet(Of Order)

End Class
Partial Public Class Order
    Public Property OrderID As Integer
    Public Property UserID As Integer
    Public Property [Date] As Date

    Public Overridable Property Customer As Customer
    Public Overridable Property OrderLineItems As ICollection(Of OrderLineItem) = New HashSet(Of OrderLineItem)

End Class
Partial Public Class OrderLineItem
    Public Property OrderID As Integer
    Public Property ProductID As Integer
    Public Property Quantity As Integer
    Public Property UnitPrice As Decimal
    Public Property IsHeld As Boolean
    Public Property IsPicked As Boolean
    Public Property IsShipped As Boolean
    Public Property PickedQuantity As Nullable(Of Integer)

    Public Overridable Property Order As Order
    Public Overridable Property Product As Product

End Class
Partial Public Class Product
    Public Property ProductID As Integer
    Public Property ProductName As String
    Public Property ProductDescription As String
    Public Property UnitPrice As Decimal
    Public Property OnHand As Integer
    Public Property UPC As String
    Public Property ProductImageUrl As String

    Public Overridable Property OrderLineItems As ICollection(Of OrderLineItem) = New HashSet(Of OrderLineItem)
    Public Overridable Property StoredProducts As ICollection(Of StoredProduct) = New HashSet(Of StoredProduct)

End Class
Partial Public Class StorageBin
    Public Property BinID As Integer
    Public Property BinLocation As Integer

    Public Overridable Property StoredProducts As ICollection(Of StoredProduct) = New HashSet(Of StoredProduct)

End Class
Partial Public Class StoredProduct
    Public Property ProductID As Integer
    Public Property BinID As Integer
    Public Property Quantity As Integer

    Public Overridable Property Product As Product
    Public Overridable Property StorageBin As StorageBin

End Class
Partial Public Class sp_helpdiagramdefinition_Result
    Public Property version As Nullable(Of Integer)
    Public Property definition As Byte()

End Class
Partial Public Class sp_helpdiagrams_Result
    Public Property Database As String
    Public Property Name As String
    Public Property ID As Integer
    Public Property Owner As String
    Public Property OwnerID As Integer

End Class
